---
# https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml

minecraftServer:
  eula: true
  difficulty: hard
  type: SPIGOT
  ops: ethan240
  spawnProtection: 4
  viewDistance: 20
  # If you adjust this, you may need to adjust resources.requests to match.
  memory: 1792M

resources:
  requests:
    memory: 2Gi
    cpu: 500m

persistence:
  annotations: {}
  ## minecraft data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  dataDir:
    # Set this to false if you don't care to persist state between restarts.
    enabled: false
    Size: 4Gi
    # existingClaim: nil
    ## specify a subpath in the volume where the data is. Useful when sharing volumes with other apps.
    # subPath: /path/to/dataDir
