#!/bin/bash

commit_message=$(cat "$1")

commit_strings="(#none|#patch|#minor|#major)"
commit_regex="^${commit_strings}"

if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
   exit 0
fi

echo -e "\e[31mCommit message must have #none, #patch, #minor or #major to perform autotagging...\e[0m"
exit 1
